### ISSUE TITLE
tools.namespace version conflict breaks lein repl

### ISSUE THREAD

**Issue by jcf** [fulcro-legacy/fulcro-template#3]
Hi Tony,

While have a play with Fulcro I decided to pull down this template and take a look around. In doing so I came across an extremely cryptic error caused by an older version of tools.namespace in my `profiles.clj`.

Running `JVM_OPTS='-Ddev' lein repl` produces the following exception:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalAccessError: clj does not exist, compiling:(fulcro_spec/watch.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
        [...snip...]
	at clojure.lang.RestFn.invoke(RestFn.java:3204)
	at fulcro_spec.runner$eval28517$loading__5569__auto____28518.invoke(runner.cljc:1)
	at fulcro_spec.runner$eval28517.invokeStatic(runner.cljc:1)
	at fulcro_spec.runner$eval28517.invoke(runner.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
        [...snip...]
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at fulcro_spec.suite$eval27058$loading__5569__auto____27059.invoke(suite.cljc:1)
	at fulcro_spec.suite$eval27058.invokeStatic(suite.cljc:1)
	at fulcro_spec.suite$eval27058.invoke(suite.cljc:1)
        [...snip...]
	at clojure.lang.RT.doInit(RT.java:475)
	at clojure.lang.RT.<clinit>(RT.java:331)
	... 1 more
Caused by: java.lang.IllegalAccessError: clj does not exist
	at clojure.core$refer.invokeStatic(core.clj:4119)
	at clojure.core$refer.doInvoke(core.clj:4087)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_lib.invokeStatic(core.clj:5755)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at fulcro_spec.watch$eval29305$loading__5569__auto____29306.invoke(watch.clj:1)
	at fulcro_spec.watch$eval29305.invokeStatic(watch.clj:1)
	at fulcro_spec.watch$eval29305.invoke(watch.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 90 more
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at leiningen.core.eval$fn__5899.invokeStatic(eval.clj:264)
	at leiningen.core.eval$fn__5899.invoke(eval.clj:260)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:366)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
	at leiningen.repl$server$fn__12003.invoke(repl.clj:243)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

That's coming from your Spec library, where you require `clj` from [`clojure.tools.namespace.find`](https://github.com/fulcrologic/fulcro-spec/blob/d8e5016ba097a07d0f1a509bdcd28859d7744bdc/src/fulcro_spec/watch.clj#L4), which I think was added in the [0.3.X](https://github.com/clojure/tools.namespace/blob/master/CHANGES.md#03x-series) series?

I've bumped the version of tools.namespace in my `profiles.clj` to fix the issue, but wonder if adding `:pedantic? :abort` to the template's `project.clj` might draw attention to where the problem really lies (in conflicting versions of dependencies). I suppose the obvious problem with that is Leiningen will suggest ignoring the newer version of the dependency, which will result in the same exception.

Would appreciate hearing your thoughts.

**Comment by awkay** [comment]
Yeah, dependencies are a pain, and user profiles have bitten most of us. I was not aware of that lein option. Given that I've not had practical experience with it, I'm more leaning towards adding something to the README reminding people that they should be careful about their profiles.

**Comment by jcf** [comment]
> Given that I've not had practical experience with it, I'm more leaning towards adding something to the README reminding people that they should be careful about their profiles.

That's fair enough. I tend to add `:abort` to all of my applications but then it's me resolving the conflicts too. If it were left to a user who's not familiar with the recent changes in each dependency the experience might not be too much better.

I'll close this issue down as I've been able to get everything up and running. Thanks, Tony!
